config/routes.rb
Rails.application.routes.draw do
  devise_for :charities, path: 'charities'
  devise_for :developers , :controllers => { :omniauth_callbacks => "callbacks" }, path: 'developers'
  root to: 'pages#home'


  resources :charities, only: [:index, :show]
  resources :projects do
    resources :reviews, only: [:create]
    resources :proposals, only: [:new, :create]
    resources :members
    resources :posts
    resources :project_skills, except: [:show, :index]
    resources :posts, except: [:show, :index]
  end
  resources :developers do
    resources :developer_skills, except: [:show, :index]
  end

  # resources :messages
  # resources :chatrooms


  get 'projects/:project_id/dashboard', to: 'projects#dashboard', as: 'projects_dashboard'
  get 'developer_dashboard', to: 'developers#dashboard', as: "developer_dashboard"
  get 'charity_dashboard', to: 'charities#dashboard', as: "charity_dashboard"

  post 'projects/:project_id/dashboard/accept', to: 'proposals#accept', as: "accept_proposal"
  post 'projects/:project_id/dashboard/reject', to: 'proposals#reject', as: "reject_proposal"

end

app/models/developer.rb
class Developer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
  has_many :proposals, dependent: :destroy

  has_many :members
  has_many :projects, through: :members
  has_many :developer_skills, dependent: :destroy
  has_many :skills, through: :developer_skills

  has_many :posts, dependent: :destroy
  # has_many :projects throgh:
  mount_uploader :avatar, PhotoUploader



  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      fullname = auth.info.name.split
      if fullname.length == 1
        user.first_name = auth.info.name
      else
        user.first_name = auth.info.name.split.first
        user.last_name = auth.info.name.split.last
      end
      user.github_username = auth.info.nickname
      user.remote_avatar_url = auth.info.image
      user.description = auth.extra.raw_info.bio
      user.save
    end
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  # after_action :verify_authorized, except: :dashboard, unless: :skip_pundit?
  def index
    @developers = Developer.all
  end

  def dashboard
    @developer = current_developer
    @projects = @developer.projects
    @proposals = @developer.proposals
    @skills = @developer.developer_skills
  end

  def show
    @developer = Developer.find(params[:id])
    @projects = @developer.projects
    @skills = @developer.developer_skills
     # @developer = Developer.find(params[:id])
     # authorize @developer
  end

  def edit
    @developer = Developer.find(params[:id])
  end

  def update
    @developer = Developer.find(params[:id])
    params[:developer][:skill_ids].reject(&:empty?).each do |skill_id|
      @developer.skills << Skill.find(skill_id)
    end
    if @developer.update(developer_params)
      redirect_to developer_dashborad_path
    else
      render :edit
    end
  end

  def teammembers(project)
    Members.all.where(project_id: project.id)
  end

  private

  def developer_params
    params.require(:developer).permit(:first_name, :last_name, :address, :description, :experience, :linkedin_username, :avatar, :birth_date, :github_username, :avatar_cache, :skill_ids)
  end

end

app/views/developers/dashboard.html.erb
<!-- <div  class="pattern" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.2) 100%), url('http://backgroundlabs.com/files/white-leather-texture-1945.png');">

  <div class="container">
      <div class="col-md-8"></div>
      <div class="col-md-4 ">
        <h1 class="stick-to-bottom"> <%= @developer.first_name %> <%= @developer.last_name %></h1>
      </div>
  </div>
</div> -->
<div >
  <figure>
    <code id="cover-image" style="display: none;"></code>
    <img class="cover-img" data-embed-id="cover-image" alt="Mastercard cover image" src="https://res.cloudinary.com/deoafyurg/image/upload/v1534472639/warren-wong-221778-unsplash.jpg">
  </figure>
<!--   <div class= "container">
  <div class="col-md-12">
    <h2 class="text-right dash-name"> <strong> <%= @developer.first_name %> <%= @developer.last_name %> </strong></h2>
  </div>
  </div> -->
</div>
<div class="container padding-large-bottom  ">



  <div class="col-md-12">
    <div class="project-info white-box">
      <!-- <div class="row" > -->

          <div class="edit-icon">
          <%= link_to edit_developer_path(current_developer) do %>
            <i class="fa fa-edit"></i>
          <% end %>
      <!-- </div> -->
      </div>
      <div class="col-md-12">
        <h2 id="dash-name"> <%= @developer.first_name %></h2>
      </div>
      <div class="row">
<!--       <div class="col-md-6">
        <h4 class="stick-to-top"><%= @developer.email %></h4>
      </div> -->
        <div class= "col-md-4 user-photo dash-photo">
          <% if @developer.avatar? %>
            <div class = "user-avatar"
            style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)),
           url('<%= cl_image_path @developer.avatar %>')">
            </div>
          <% else %>
            <%= image_tag "https://image.flaticon.com/icons/svg/145/145849.svg", class: "user-avatar"%>
          <% end %>
          <div class = "star-rating">
            <%= link_to "Preview profile", developer_path(@developer), class: 'btn btn-reset btn-top-margin'  %>
          </div>
        </div>
        <div class="col-md-8 dev-description">
          <h4 class= "project-h4" > <strong> Bio </strong></h4>
          <h4 class="stick-to-top"> <%= @developer.description %></h4>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="project-info white-box">
      <h3 >MY PROJECTS</h3>
      <div class = "row">
      <% @projects.each do |project| %>
        <div class="col-md-4  text-center projects-box">
          <h3><%= project.name  %> </h3>
          <p>Status: <%= project.status %></p>
          <p>Deadline: <%= project.deadline  %></p>
          <%= link_to "", projects_dashboard_path(project), class: 'box-link'  %>
        </div>
      <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="skills white-box">
      <h3> MY SKILLS </h3>
      <div class="form-group">
        <div class="skill-display">
          <% @skills.each do |skill| %>
            <div  id="<%= skill.id %>" class = "text-center">
              <div class="skill-choice"><i class="devicon-<%= skill.skill.name %>-plain colored"></i>  <%= skill.skill.name %>
                <div class= "remove-button">
                   <%= link_to developer_developer_skill_path(@developer, skill) ,confirm: "Are you sure?", method: :delete, remote: true do %>
                     <i class="far fa-times-circle"></i>
                   <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <i class="fas fa-plus add-skill" data-toggle="modal" data-target="#myModal">
            <h4 class = "padding-add-left"> Add more</h4>
          </i>
        </div>
      </div>
    </div>
  </div>



  <div class="col-md-12">
    <div class="project-info white-box">
      <h3>MY APPLICATIONS</h3>
      <div class = "row">
      <% @proposals.each do |proposal| %>
        <div class="col-md-4  text-center projects-box">
          <h3><%= proposal.project.name  %> </h3>
          <p>State: <%= proposal.state %></p>
          <%= link_to "", project_path(proposal.project), class: 'box-link'  %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
  </div>
</div>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Choose skills</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for ([@developer,DeveloperSkill.new])  do |f| %>
          <div class="form-group">
            <label class="control-label check_boxes optional">
                <h1>Skills</h1>
            </label>
            <input type="hidden" name="developer[skill_ids][]" value="">
            <fieldset class="skill-choices">
              <% Skill.all.each do |skill| %>
                <div class="skill-choice">
                  <input type="checkbox" class="checkbox-hidden" value="<%= skill.id%>" name="developer[skill_ids][]" id="developer_skill_ids_<%= skill.id%>" >
                  <label class="" for="developer_skill_ids<%= skill.id%>">
                    <%= skill.name %>
                  </label>
                </div>
              <% end %>
            </fieldset>
          </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-reset" data-dismiss="modal">Close</button>
         <%= f.button :submit, "Update", class: "btn btn-success" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/developers/edit.html.erb
<div class="container padding-large-bottom">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-post text-center">
        <%= image_tag "logo.png", height: 70 %>
        <h2>Edit profile</h2>
        <%= simple_form_for(@developer) do |f| %>
          <%= f.error_notification %>

          <div class="row">
            <div class="col-xs-6">
              <h1><%= f.input :first_name, required: false %></h1>
            </div>
            <div class="col-xs-6">
              <h1><%= f.input :last_name, required: false %></h1>
            </div>
            <div class="col-xs-6">
              <h1><%= f.input :github_username, required: false %></h1>
            </div>
            <div class="col-xs-6">
              <h1><%= f.input :linkedin_username, required: false %></h1>
            </div>
            <div class="col-xs-12">
              <h1><%= f.input :address, required: false %></h1>
            </div>
            <div class="col-xs-12">
              <h1><%= f.input :description, required: false %></h1>
            </div>
            <div class="col-xs-12">
              <h1><%= f.input :experience, required: false %></h1>
            </div>
            <div class="col-xs-12">
              <h1><%= f.input :avatar, required: false, placeholder:"Select date" %></h1>
              <%= f.input :avatar_change, as: :hidden %>
            </div>
            <div class="col-xs-12">
              <h1><%= f.input :birth_date, as: :string, placeholder: "#{Date.today.strftime('%m/%d/%Y')}", required: false, input_html: {class: "datepicker"} %></h1>
            </div>


            <div class="form-group">
              <label class="control-label check_boxes optional">
                <h1 class = "margin-bottom">Skills</h1>
              </label>
              <input type="hidden" name="developer[skill_ids][]" value="">
              <fieldset class="skill-choices">
                <% Skill.all.each do |skill| %>
                  <div>
                    <div class="skill-choice">
                      <input type="checkbox" class="checkbox-hidden" value="<%= skill.id%>" name="developer[skill_ids][]" id="developer_skill_ids_<%= skill.id%>" >
                      <label class="" for="developer_skill_ids<%= skill.id%>">
                        <i class="devicon-<%= skill.name %>-plain colored"></i>
                        <%= skill.name %>
                      </label>
                    </div>
                  </div>
                <% end %>
              </fieldset>
            </div>

            <div class="col-xs-6">
              <div class="form-actions">
                <%= f.button :submit, "Update", class: "btn btn-success" %>
              </div>
            </div>

          <% end %>
          <div class="col-xs-6">
            <%= link_to "Back", :back, class: "btn btn-reset" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/developers/show.html.erb
<figure>
  <code id="cover-image" style="display: none;"></code>

  <img class="cover-img" data-embed-id="cover-image" alt="Mastercard cover image" src="https://res.cloudinary.com/deoafyurg/image/upload/v1534410963/filip-varga-271263-unsplash.jpg">

</figure>

<div class="container">

  <div class="col-md-12">
    <div class="project-info white-box">
      <div class="col-md-4">
      </div>
        <div class="col-md-8">
        </div>
      <div class = "row padding-medium-top" >
        <div class="col-md-4 user-photo">
          <% if @developer.avatar? %>
            <div class = "user-avatar"
            style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)),
           url('<%= cl_image_path @developer.avatar %>')"></div>
          <% else %>
            <%= image_tag "https://image.flaticon.com/icons/svg/145/145849.svg", class: "user-avatar"%>
          <% end %>
          <div class = "star-rating">
            <div class="fa fa-star on"></i><i class="fa fa-star on"></i><i class="fa fa-star on"></i><i class="fa fa-star on"></i><i class="fa fa-star off"></i></div>
          </div>
        <div class="contact-links contact-links-show ">
          <a href="#"><i class="far fa-envelope"></i> </a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin-in"></i></a>
          <a href="#"><i class="fab fa-github"></i></a>
        </div>
        </div>
        <div class="col-md-8">
          <div>
            <h3 class="margin-remove-top"> <%= @developer.first_name %> <%= @developer.last_name %></h3>
            <h4 class= "project-h4" > <strong> Bio </strong></h4>
            <h4 class= "project-h4"><%= @developer.description %></h4>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="project-info white-box">
      <div>
        <h3> <%= @developer.first_name %>'s Experience </h3>
        <h4 class= "project-h4 show-content"><%= @developer.experience %></h4>
      </div>
    </div>
  </div>


  <div class="col-md-12">
    <div class="project-info white-box">
      <h3> <%= @developer.first_name %>'s projects </h3>
      <div class="row">
        <div class="form-group">
          <% @projects.each do |project| %>
            <div class="col-md-3  text-center projects-box">
              <h3><%= project.name  %> </h3>
              <p>Status: <%= project.status %></p>
              <p>Deadline: <%= project.deadline  %></p>
              <%= link_to "", project_path(project), class: 'box-link'  %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="project-info white-box dev-skills-show">
      <h3>  <%= @developer.first_name %>'s skills </h3>
      <div class="skill-display">
        <% @developer.skills.each do |skill| %>
          <div class = "text-center">
            <div class="skill-choice">
              <i class="devicon-<%= skill.name %>-plain colored"></i>
              <%= skill.name %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>