config/routes.rb
Rails.application.routes.draw do
  devise_for :charities, path: 'charities'
  devise_for :developers , :controllers => { :omniauth_callbacks => "callbacks" }, path: 'developers'
  root to: 'pages#home'


  resources :charities, only: [:index, :show]
  resources :projects do
    resources :reviews, only: [:create]
    resources :proposals, only: [:new, :create]
    resources :members
    resources :posts
    resources :project_skills, except: [:show, :index]
    resources :posts, except: [:show, :index]
  end
  resources :developers do
    resources :developer_skills, except: [:show, :index]
  end

  # resources :messages
  # resources :chatrooms


  get 'projects/:project_id/dashboard', to: 'projects#dashboard', as: 'projects_dashboard'
  get 'developer_dashboard', to: 'developers#dashboard', as: "developer_dashboard"
  get 'charity_dashboard', to: 'charities#dashboard', as: "charity_dashboard"

  post 'projects/:project_id/dashboard/accept', to: 'proposals#accept', as: "accept_proposal"
  post 'projects/:project_id/dashboard/reject', to: 'proposals#reject', as: "reject_proposal"

end

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container align-top footer-container">
    <div class="row">

      <div class="footer-left col-md-4" >
        <%= image_tag "logo.png", height: 70 %>
        <p>We <s>create</s> update the world we live in</p>
      </div>

      <div class="col-md-2">
        <h4>Explore</h4>
        <ul>
        <li>Home</li>
        <li>All Projects</li>
        <li>Who We Are</li>
        <li>How It Works</li>
        <li>Careers</li>
        </ul>
      </div>

      <div class="col-md-2">
        <h4>Visit Us</h4>
        <p class="footer-address">Jalan Batu Mejan No. 88, Canggu, Kuta Utara, Bali 80361</p>
      </div>

      <div class="col-md-2">
        <h4>Legal</h4>
         <ul>
        <li>Terms</li>
        <li>Privacy</li>
        </ul>
      </div>

      <div class="col-md-2">

        <div class="footer-right-part">

          <div class="footer-links">
            <h4>Follow Us</h4>
            <div>
              <a href="#"><i class="fab fa-github"></i></a>
              <a href="#"><i class="fab fa-instagram"></i></a>
              <a href="#"><i class="fab fa-facebook"></i></a>
              <a href="#"><i class="fab fa-twitter"></i></a>
              <a href="#"><i class="fab fa-linkedin"></i></a>
            </div>
          </div>


          <div class="email">
            <input type="text" placeholder="Subscribe">
            <svg viewBox="0 0 16 16">
                <path d="M10.8000002,10.8000002 C9.85000038,11.6500006 9.18349609,12 8,12 C5.80000019,12 4,10.1999998 4,8 C4,5.80000019 5.80000019,4 8,4 C10.1999998,4 12,6 12,8 C12,9.35332031 12.75,9.5 13.5,9.5 C14.25,9.5 15,8.60000038 15,8 C15,4 12,1 8,1 C4,1 1,4 1,8 C1,12 4,15 8,15 C12,15 15,12 15,8"></path>
                <polyline points="5 8.375 7.59090909 11 14.5 4" transform='translate(0 -0.5)'></polyline>
            </svg>
          </div>

        </div>

      </div>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada|Montserrat:400,500" rel="stylesheet">

<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <!-- <img src="logomakr.com/2EdbyK" alt="home"> -->
    <%= image_tag "logo.png", height: 70, class: "logo" %>
    <%= image_tag "logo_white.png", height: 70, class: "logo-white" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
<!--
    <a href="/" class="navbar-wagon-item navbar-wagon-link">Home</a> -->
    <a href="/projects/" class="navbar-wagon-item navbar-wagon-link">All projects</a>

    <!-- When developer is signed in -->

    <% if developer_signed_in? %>
      <div class="navbar-wagon-item navbar-wagon-link">
        <div class="dropdown display-flex">
          <% if current_developer.avatar.file %>
            <div class="avatar dropdown-toggle" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path current_developer.avatar %>')" id="navbar-wagon-menu" data-toggle="dropdown"></div>
          <% else %>
            <%= image_tag "https://image.flaticon.com/icons/svg/145/145849.svg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <span class="dropdown-toggle" data-toggle="dropdown"><%= current_developer.first_name %></span>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to developer_dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: " Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_developer_path(current_developer) do %>
                <i class="fa fa-cog"></i><%= t(".profile", default: " Edit profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_developer_session_path, method: :delete do %>
                <i class="fas fa-sign-in-alt"></i></i>  <%= t(".sign_out", default: " Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <!-- When charity is signed in -->

    <% elsif charity_signed_in?%>
      <div class="navbar-wagon-item navbar-wagon-link">
        <div class="dropdown">
          <% if current_charity[:photo]%>
            <%= image_tag "#{current_charity.photo}", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% else %>
              <%= image_tag "https://albertonrecord.co.za/wp-content/uploads/sites/35/2016/11/Charities-as-a-Vehicle-for-a-Social-Enterprise-1.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% end %>
          <span class="dropdown-toggle" data-toggle="dropdown"><%= current_charity.name %></span>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to charity_dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>

            <li>
              <%= link_to edit_charity_registration_path(current_charity) do %>
                <i class="fa fa-cog"></i><%= t(".profile", default: "Edit profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_charity_session_path, method: :delete do %>
                <i class="fas fa-sign-in-alt"></i></i>  <%= t(".sign_out", default: " Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <!-- When no one is signed in -->

    <% else %>
      <%#= link_to t(".sign_in", default: "Developer login"), new_developer_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <a class="navbar-wagon-item navbar-wagon-link" href="/developers/auth/github">Sign in with GitHub <i class="fab fa-github login-icon"></i></a>
      <%= link_to t(".sign_in", default: "Charity login"), new_charity_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>