config/routes.rb
Rails.application.routes.draw do
  devise_for :charities, path: 'charities'
  devise_for :developers , :controllers => { :omniauth_callbacks => "callbacks" }, path: 'developers'
  root to: 'pages#home'


  resources :charities, only: [:index, :show]
  resources :projects do
    resources :reviews, only: [:create]
    resources :proposals, only: [:new, :create]
    resources :members
    resources :posts
    resources :project_skills, except: [:show, :index]
    resources :posts, except: [:show, :index]
  end
  resources :developers do
    resources :developer_skills, except: [:show, :index]
  end

  # resources :messages
  # resources :chatrooms


  get 'projects/:project_id/dashboard', to: 'projects#dashboard', as: 'projects_dashboard'
  get 'developer_dashboard', to: 'developers#dashboard', as: "developer_dashboard"
  get 'charity_dashboard', to: 'charities#dashboard', as: "charity_dashboard"

  post 'projects/:project_id/dashboard/accept', to: 'proposals#accept', as: "accept_proposal"
  post 'projects/:project_id/dashboard/reject', to: 'proposals#reject', as: "reject_proposal"

end

app/models/project.rb
class Project < ApplicationRecord
  STATUSES = ['Pending', 'Active', 'Done', 'In Progress']
  TYPES = ['Rebuild', "New", "Update"]
  CATEGORIES = ["Animals", "Community Development", "Education", "Health", "Environment", "Human Rights"]
  DEADLINES = [15, 30, 60]
  SKILLS = ["angularjs", "backbonejs", "bootstrap", "c", "csharp", "css3", "django", "drupal", "git", "gitlab", "heroku", "html5", "java", "javascript", "jquery", "linux", "meteor", "mongodb", "mysql", "nodejs", "php", "python", "rails", "react", "ruby", "swift", "typescript", "vim", "vuejs", "webpack", "wordpress"]

  belongs_to :charity
  has_many :members, dependent: :destroy
  has_many :developers, through: :members
  has_many :project_skills
  has_many :skills, through: :project_skills
  has_many :chatrooms
  has_many :proposals
  has_many :posts
  mount_uploader :photo, PhotoUploader

  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # before_action :authenticate_charity!, only: [:new, :create, :edit, :update, :destroy]

  skip_before_action :authenticate!, only: [:index, :show]

  def index
    @projects = policy_scope(Project)
    @projects = @projects.where(nil)
    if params[:address].present?
      @charities = Charity.where("address LIKE ?", "%#{params[:address]}%")
      @projects = @projects.where(charity_id: @charities.pluck(:id))
    end
    # if !params[:charities].present?
    @projects = @projects.where(status: params[:status]) if params[:status].present?
    @projects = @projects.where(work_type: params[:work_type]) if params[:work_type].present?
    if params[:category].present?
      @charities = Charity.where(category: params[:category])
      @projects = @projects.where(charity_id: @charities.pluck(:id))
    end
    # if params[:skill].present?
    #   @skills = Skill.where(name: params[:skill])
    #   @projects = @projects.where(project_skill_id: @skills.pluck(:id))
    # end
    if params[:skill].present?
     @skill = Skill.where(name: params[:skill]).first
     projects = @projects
     @projects = @skill.projects
   end

    if params[:deadline].present?
        @projects = @projects.where("deadline <= ? ", Date.today + params[:deadline].to_i.day)
    end
    # elsif params[:charities].present?
    #   @projects = @projects.where(id: params[:projects])
    #   @projects = @projects.where(status: params[:status]) if params[:status].present?
    #   @projects = @projects.where(work_type: params[:work_type]) if params[:work_type].present?
    #   if params[:category].present?
    #     @charities = Charity.where(category: params[:category])
    #     @projects = @projects.where(charity_id: @charities.pluck(:id))
    #   end
    #   if params[:skill].present?
    #     @skills = Skill.where(name: params[:skill]).first
    #     projects = @projects
    #     @projects = @skill.projects
    #   end
    #   if params[:deadline].present?
    #       @projects = @projects.where("deadline <= ? ", Date.today + params[:deadline].to_i.day)
    #   end
    # end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    @project = Project.find(params[:id])
    authorize @project
    @skills = @project.skills
    @charity = @project.charity
    @posts = @project.posts
    @markers =
      [{
        lat: @charity.latitude,
        lng: @charity.longitude#,
        # infoWindow: { content: render_to_string(partial: "/carities/map_box", locals: { charity: charity }) }
      }]
    @charity_id = Charity.where(category: @charity.category).pluck(:id)
    @similar_projects = Project.where(charity_id: @charity_id)
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
  end

  def update
    @project = Project.find(params[:id])
    authorize @project
    # params[:project][:skill_ids].reject(&:empty?).each do |skill_id|
    #   @project.skills << Skill.find(skill_id)
    # end
    if @project.update(project_params)
      redirect_to projects_dashboard_path(@project)
    else
      render :edit
    end
  end

  def new
    @project = Project.new
    # authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.charity = current_charity
    # authorize @project
    if @project.save
      puts "Your project has been created!"
      redirect_to projects_dashboard_path
    else
      render :new
    end
  end

  def dashboard
    @project = Project.find(params[:project_id])
    # authorize @project
    @proposals = @project.proposals
    # authorize @project
    @charity = @project.charity
    @skills = @project.project_skills
    @posts = Post.all
    @charity_id = Charity.where(category: @charity.category).pluck(:id)
    @similar_projects = Project.where(charity_id: @charity_id)
  end

  private
  def project_params
    params.require(:project).permit(:type, :status, :github, :deadline, :charity_id, :name, :details, :skill_ids)
  end
end

app/views/projects/_project_list.html.erb
<% projects.each do |project| %>

  <div class="card-index-container">
    <div class="card-index-charity">
      <% if project.charity.logo.model[:logo] %>
        <div class= "avatar-small" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path project.charity.logo %>')">
        </div>
        <%#= cl_image_tag "project.charity.logo", width: "50", height: "50" %>
      <% else %>
        <%= image_tag "https://image.shutterstock.com/image-vector/people-charity-logo-template-design-260nw-612981149.jpg", width: "50", height: "50" %>
      <% end %>


      <p><%= project.charity.name %></p>
    </div>
    <p class="card-index-category"><%= project.charity.category %></p>
    <p class="card-index-type"><%= project.work_type %></p>
    <div class="card-index-project">
      <h2><%= link_to project.name%></h2>
      <p class="mute-75"><%= project.details %></p>
    </div>
    <div class="card-index-details">
      <p class="card-index-deadline"><%= project.deadline %></p>
      <p class="card-index-progess"><%= project.status %></p>
    </div>
    <%= link_to "", project_path(project), class:"card-hover"%>
  </div>
<%end %>

app/views/projects/dashboard.html.erb
<figure>
  <code id="cover-image" style="display: none;"></code>
  <img class="cover-img" data-embed-id="cover-image" alt="Mastercard cover image" src="https://images.unsplash.com/photo-1533562179840-9cce77549aa6?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1600&h=400&fit=crop&ixid=eyJhcHBfaWQiOjF9&s=461c16b2ba620b62655c9c0ad08ddd78">
</figure>

<div class="container padding-large-bottom">

  <div class="row row-eq-height project-show-conatiner">


    <div class="col-md-12">
      <div class="row">
        <div class="col-md-12">
          <div class="project-info-dahsboard white-box">
            <div class="col-md-9 pr-title">
              <h3><%= @project.name %></h3>
            </div>
            <div class="row">
              <div class="col-md-12">
                <p class= "pr-sml-title">Project details:</p>
                <p> <%= @project.details %></p>
                <p class= "pr-sml-title">Type of project: </p>
                <p><%= @project.work_type %></p>
              </div>
            </div>
            <div class = "days-left">
              <p><%= @project.status  %></p>
              <p> <%= (@project.deadline - Date.today).to_i %> days left</p>
            </div>
          </div>
        </div>

        <div class="col-md-12">
          <div class="skills white-box ">
            <h3>Skills required</h3>
            <div class="form-group">
              <div class="skill-display">
                <% @skills.each do |project_skill| %>
                  <div  id="<%= project_skill.id %>" class = "text-center">
                    <div class="skill-choice"><i class="devicon-<%= project_skill.skill.name %>-plain colored"></i>  <%= project_skill.skill.name %>
                      <div class= "remove-button">
                         <%= link_to project_project_skill_path(@project, project_skill) ,confirm: "Are you sure?", method: :delete, remote: true do %>
                           <i class="far fa-times-circle"></i>
                         <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
                <i class="fas fa-plus add-skill" data-toggle="modal" data-target="#myModal">
                  <h4 class = "padding-add-left"> Add more</h4>
                </i>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-12">
          <div class="charity-info-dashboard white-box ">
            <div class="row">
              <div class = "col-md-4">
                <div class="charity-logo-center">
                  <% if @project.charity.logo? %>
                    <%= cl_image_tag @project.charity.logo, class: "user-avatar-sml" %>
                  <% else %>
                    <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjFbGzCB7sAeKl1FMboHXQiDZ3KSd7G5CPmNOZ_EGBLY3fzTOjxQ", width: 300%>
                  <% end %>
                </div>
              </div>
              <div class = "col-md-8 text-right">
                <h3><%= @charity.name %></h3>
                <h4><%= @project.charity.category %></h4>
                <p><%= @project.charity.address %></p>
                <p><%= @project.charity.email %></p>
                <p><%= @project.charity.website %></p>
              </div>
            </div>
          </div>
        </div>`
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="team-info white-box">
        <h3 class = "text-center">Team Members: </h3>
        <div class = "row">
          <div class ="form-group">
            <% if @project.members.size == 0 %>
              <h4 class = "text-center">No developers working on this project yet</h4>
            <% else %>
              <% @project.members.each do |member| %>
                <div class="col-md-4  text-center team-member">
                  <div class="team-member-profile">
                    <% if member.developer.avatar? %>
                      <%= cl_image_tag member.developer.avatar, class: "user-avatar" %>
                    <% else %>
                      <%= image_tag "https://image.flaticon.com/icons/svg/145/145849.svg", class: "user-avatar"%>
                    <% end %>
                    <div class = "team-member-info">
                      <p><%= member.developer.first_name %> <%= member.developer.last_name %></p>
                      <% if @project.leader_id == member.developer.id %>
                        <h4> LEADER </h4>
                      <% end %>
                    </div>
                    <%= link_to "", developer_path(member.developer), class: "clickable" %>
                  </div>
                <% if policy(member).destroy? && current_developer != member.developer%>
                  <%= link_to "Remove from the team", project_member_path(@project, member.developer), method: :delete, class: 'btn btn-reset', data: { confirm: "Are you sure?" } %>
                <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="applications-info white-box">
        <h3 class = "text-center">New join requests: </h3>
        <div class = "row">
          <div class ="form-group">
            <% if @proposals.where(state: "pending").size == 0  %>
                <h4 class = "text-center">No new applications</h4>
            <% else %>
              <% @proposals.each do |proposal| %>
                <% if proposal.state.downcase == "pending" &&  policy(proposal).accept? %>
                  <div class="col-md-3 text-center application-card ">
                    <div class="team-member-profile">
                      <% if proposal.developer.avatar? %>
                        <%= cl_image_tag proposal.developer.avatar, class: "user-avatar-xs black-n-white" %>
                      <% else %>
                        <%= image_tag "https://image.flaticon.com/icons/svg/145/145849.svg", class: "user-avatar-xs black-n-white"%>
                      <% end %>
                      <p><%=proposal.developer.first_name %></p>
                      <%= link_to "", developer_path(proposal.developer), class: "clickable" %>
                    </div>
                    <%= link_to "Accept ", accept_proposal_path(proposal: proposal), method: :post, class: 'btn btn-success' %>
                    <%= link_to "Reject", reject_proposal_path(proposal: proposal), method: :post, class: 'btn  btn-reset' %>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>


    <div class="col-md-12">

      <div class="comments white-box">
         <h3> Comments: </h3>
        <ul class="post-list green-background">
          <div class = "border-spaced">
            <div class = "row">
              <div class = "col-md-8">
                <p>Content</p>
              </div>
              <div class = "col-md-2">
                <p>Developer</p>
              </div>
              <div class = "col-md-2">
                <p>Created on</p>
              </div>
            </div>
          </div>
          <% if @posts %>
            <% @posts.each do |post| %>
              <% if post.project == @project %>
                <div class = "row">
                  <li class="">
                    <div class = "border-spaced-bottom">
                      <div class = "col-md-8">
                        <%= post.content %>
                      </div>
                      <div class = "col-md-2">
                        <%= post.developer.first_name %>
                      </div>
                      <div class = "col-md-2">
                        <%= post.created_at.strftime("%D %T") %>
                      </div>
                  </div>
                  </li>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </ul>
        <div class= "post-footer">
          <button type="button" class="btn btn-success text-right" data-toggle="modal" data-target=".bs-example-modal-lg">Add a post</button>
        </div>
      </div>
    </div>
  </div>


  <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Post a comment</h4>
        </div>

        <div class="modal-body">
          <%= simple_form_for [@project, Post.new] do |f| %>
            <%= f.input :content %>
        </div>
        <div class="modal-footer form-inline">
            <%= f.submit "Post", class: "btn btn-primary" %>
          <% end %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Choose skills</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for ([@project,ProjectSkill.new])  do |f| %>
          <div class="form-group">
            <label class="control-label check_boxes optional">
                <h1>Skills</h1>
            </label>
            <input type="hidden" name="project[skill_ids][]" value="">
            <fieldset class="skill-choices">
              <% Skill.all.each do |skill| %>
                <div class="skill-choice">
                  <input type="checkbox" class="checkbox-hidden" value="<%= skill.id%>" name="project[skill_ids][]" id="project_skill_ids_<%= skill.id%>" >
                  <label class="" for="project_skill_ids<%= skill.id%>">
                    <%= skill.name %>
                  </label>
                </div>
              <% end %>
            </fieldset>
          </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-reset" data-dismiss="modal">Close</button>
         <%= f.button :submit, "Update", class: "btn btn-success" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-post text-center">
        <%= image_tag "logo.png", height: 70 %>
        <h2>Edit the project</h2>
        <%= simple_form_for @project do |f| %>
          <h1><%= f.input :name %></h1>
          <h1><%= f.input :details %></h1>
          <h1><%= f.input :status %></h1>
          <h1><%= f.input :work_type %></h1>
          <h1><%= f.input :deadline, as: :string, required: false, input_html: {class: "datepicker"} %></h1>

            <div class="form-group">
              <label class="control-label check_boxes optional">
                  <h1>Skills</h1>
              </label>
              <input type="hidden" name="project[skill_ids][]" value="">
              <fieldset class="skill-choices">
                <% Skill.all.each do |skill| %>
                  <div class="skill-choice">
                    <input type="checkbox" class="checkbox-hidden" value="<%= skill.id%>" name="project[skill_ids][]" id="project_skill_ids_<%= skill.id%>" >
                    <label class="" for="project_skill_ids<%= skill.id%>">
                      <%= skill.name %>
                      <i class="fa fa-check"></i>
                    </label>
                  </div>
                <% end %>
              </fieldset>
            </div>

          <h1><%= f.button :submit, class: 'btn btn-success' %></h1>
          <%= link_to "Back", :back, class: "btn btn-reset" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.js.erb
function renderProjects(html) {
  const projects = document.getElementById('filter');
  console.log(projects, html)
  projects.innerHTML = html;
}

  renderProjects('<%= j render "projects/project_list", projects: @projects %>');

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3 class="text-center">Enter your project details:</h3>

      <%= simple_form_for @project do |f| %>
        <%= f.label :name, 'Project Name' %>:
        <%= f.input :name, label: false, required: true %>
        <%= f.label :details, 'Project Details' %>:
        <%= f.input :details, label: false, required: true %>
        <%= f.label :work_type, 'Type of Project' %>:
        <%= f.input :work_type, collection: ["New Website", "Rebuild Existing Website", "Improve Existing Website"], label: false %>
        <%= f.input :deadline %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>

  </div>
</div>

app/views/projects/show.html.erb
<figure>
  <code id="cover-image" style="display: none;"></code>
  <img class="cover-img" data-embed-id="cover-image" alt="Mastercard cover image" src="https://images.unsplash.com/photo-1533562179840-9cce77549aa6?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1600&h=400&fit=crop&ixid=eyJhcHBfaWQiOjF9&s=461c16b2ba620b62655c9c0ad08ddd78">
</figure>


<div class="container padding-large-bottom">
  <div class="row row-eq-height project-show-conatiner">


    <div class="col-md-9">
      <div class="row">
        <div class="col-md-12">
          <div class="project-show-box white-box">
            <h2 class=""><%= @project.name %></h2>
              <div class="row">
              <div class="col-md-3">
                <div class="project-show-logo">
                  <% if @project.charity.logo.model[:logo] %>
                    <div class= "charity-avatar-lg col-md-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @project.charity.logo %>')">
                    </div>
                    <%#= cl_image_tag @project.charity.logo, class: "charity-avatar-lg" %>
                  <% else %>
                    <%= image_tag "https://image.shutterstock.com/image-vector/people-charity-logo-template-design-260nw-612981149.jpg", width: "100", height: "100" %>
                  <% end %>
                </div>
              </div>
              <div class="project-show-content col-md-6">
                <h3 class= "project-h3"><%= @project.charity.name %></h3>
                <div class="contact-links">
                  <!-- <a href="#"><i class="far fa-envelope"></i>   <% @project.charity.email %></a>
                  <a href="#"><i class="fas fa-desktop"></i>   <% @project.charity.website %></a> -->
                  <a href="mailto: <%= @project.charity.email %>" ><i class="far fa-envelope"></i></a>
                  <a href="<%= @project.charity.website %>" target="_blank"><i class="fas fa-desktop"></i></a>
                  <a href="#"><i class="fab fa-instagram"></i></a>
                  <a href="#"><i class="fab fa-facebook"></i></a>
                  <a href="#"><i class="fab fa-twitter"></i></a>
                  <a href="#"><i class="fab fa-github"></i></a>
                </div>
              </div>
              <div class="show-apply col-md-3">
                <%# if policy(Proposal.new(project: @project)).create? %>
                  <button type="button" class="btn btn-success show-buttons" data-toggle="modal" data-target="#myModal">
                    Apply
                  </button>
                <%# end %>
              </div>
              </div>
          </div>
        </div>

        <div class="col-md-12">
          <div class="white-box project-info">
            <div class="row">
              <div class=" col-md-10">
                <h3 class= "project-h3">Project Details</h3>
                <p><%= @project.details %></p>
                <p class="italic"> end by <%= @project.deadline %></p>
              </div>
              <div class="col-md-2 text-center">
                <p  class="pr-status"> <%= @project.status%></p>
                <p> <%= @project.work_type %></p>
                <p class="pr-shots">Screenshots:</p>
                <div class="thumbnail" data-src="<%= cl_image_path @project.photo %>">
                  <%= cl_image_tag @project.photo, width: "100", height: "100"%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="similar-projects">
        <div class="text-center arrows">
          <div class="arrow">
            <% if @project.previous %>
              <%= link_to project_path(@project.previous) do %>
                <i class="fas fa-arrow-left"></i>
              <% end %>
              <% end %>
          </div>
          <div class="arrow">
            <%= link_to "All", projects_path %>
          </div>
          <div class="arrow">
            <% if @project.next %>
              <%= link_to project_path(@project.next) do %>
                <i class="fas fa-arrow-right"></i>
              <% end %>
            <% end %>
          </div>
        </div>

        <h2  class = "margin-bottom"> Similar projects</h2>
        <% @similar_projects.each do |project|%>
          <% if project != @project %>
            <div class="similar-projects-box mute-75">
              <p><%= project.name%></p>
              <p><%= project.charity.name %></p>
              <p><%= project.deadline %></p>
              <%= link_to "", project_path(project), class:"similar-project-link"%>
            </div>
          <% end %>
          <br>
        <% end %>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="white-box">
        <h3 class= "project-h3">More About <%= @project.charity.name %></a></h3>
        <p><%= @project.charity.description %></p>
      </div>
    </div>

    <div class="col-md-12">
      <div class="white-box">
        <h3 class= "project-h3"> Skills Required </h3>
        <div class="form-group">
          <div class="skill-display">
            <% @project.skills.each do |skill| %>
              <div class = "text-center">
                <div class="skill-choice"><i class="devicon-<%= skill.name %>-plain colored"></i>  <%= skill.name %></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="team-info white-box">
        <h3 class = "text-center">Team Members: </h3>
        <div class = "row">
          <div class ="form-group">
            <% if @project.members.size == 0 %>
              <h4 class = "text-center">No developers working on this project yet</h4>
            <% else %>
              <% @project.members.each do |member| %>
                <div class="col-md-4 text-center team-member">
                  <div class="team-member-profile">
                    <% if member.developer.avatar? %>
                      <%= cl_image_tag member.developer.avatar, class: "user-avatar" %>
                    <% else %>
                      <%= image_tag "https://image.flaticon.com/icons/svg/145/145849.svg", class: "user-avatar"%>
                    <% end %>
                    <div class = "team-member-info">
                      <p><%= member.developer.first_name %> <%= member.developer.last_name %></p>
                      <% if @project.leader_id == member.developer.id %>
                        <h4> LEADER </h4>
                      <% end %>
                    </div>
                    <%= link_to "", developer_path(member.developer), class: "clickable" %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>


    <div class="col-md-12">
      <div id="map" data-markers=<%= @markers.to_json %>> Here the map</div>
    </div>

    <div class="col-md-12 text-center">
      <% if policy(@project).dashboard? %>
        <%= link_to "Dashboard", projects_dashboard_path(@project), class:'btn btn-success show-buttons'  %>
      <% end %>
    <% if policy(@project).edit? %>
      <%= link_to "Edit", edit_project_path(@project), class:'btn btn-default show-buttons'  %>
      <% end %>
    </div>
    <div class="show-apply col-md-12">
    <%# if policy(Proposal.new(project: @project)).create? %>
      <button type="button" class="btn btn-success show-buttons" data-toggle="modal" data-target="#myModal">
        Apply
      </button>
    <%# end %>
    </div>


    <div class="col-md-12">

      <div class="comments white-box">
        <h3> Project updates </h3>
        <ul class="post-list green-background">
          <% if @posts.count > 0 %>
            <div class = "border-spaced">
              <div class = "row">
                <div class = "col-md-8">
                  <p>Content</p>
                </div>
                <div class = "col-md-2">
                  <p>Developer</p>
                </div>
                <div class = "col-md-2">
                  <p>Created on</p>
                </div>
              </div>
            </div>
            <% @posts.each do |post| %>
              <div class = "row">
                <li class="">
                  <div class = "border-spaced-bottom">
                    <div class = "col-md-8">
                      <%= post.content %>
                    </div>
                    <div class = "col-md-2">
                      <%= post.developer.first_name %>
                    </div>
                    <div class = "col-md-2">
                      <%= post.created_at.strftime("%D %T") %>
                    </div>
                  </div>
                </li>
              </div>
            <% end %>
          <% else %>
            <h4 class = "text-center">No updates yet</h3>
          <% end %>
        </ul>
      </div>
    </div>

  </div>




  <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Confirm your application</h4>
        </div>
        <div class="modal-body">
          <p>After you apply you will have to wait to be accpeted as part of the team working on <strong><%= @project.name %> </strong></p>
        </div>
        <div class="modal-footer">
            <%= link_to "Apply", project_proposals_path(@project), method: :post, class:"btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</div>